function C = C_calc_func(x,y,th1,th2,ph1,ph2,dx,dy,dth1,dth2,dph1,dph2)
%C_calc_func
%    C = C_calc_func(X,Y,TH1,TH2,PH1,PH2,DX,DY,DTH1,DTH2,DPH1,DPH2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    23-Jul-2025 14:08:31

t2 = cos(ph1);
t3 = sin(ph1);
t4 = sin(ph2);
t5 = dph1+dth1;
t6 = dph2+dth2;
t7 = ph1+th1;
t8 = ph2+th2;
t9 = cos(t7);
t10 = cos(t8);
t11 = sin(t7);
t12 = sin(t8);
t13 = t3.*(1.19e+2./6.25e+2);
t14 = t2.*1.63e-3;
t15 = t13+t14;
et1 = -dth2.*(dph2.*t10.*4.580069e-2+dth2.*(t10.*4.580069e-2+cos(th2).*6.67832684e-2))-dth1.*(dph1.*(t9.*(2.38e+2./6.25e+2)-t11.*3.26e-3).*2.49975e-1+dth1.*(t9.*9.519048e-2-t11.*8.149185e-4+cos(th1).*9.35690184e-2));
et2 = dph1.*t5.*(t9.*(1.19e+2./6.25e+2)-t11.*1.63e-3).*(-4.9995e-1)-dph2.*t6.*t10.*4.580069e-2;
et3 = -dth2.*(dph2.*t12.*4.580069e-2+dth2.*(t12.*4.580069e-2+sin(th2).*6.67832684e-2))-dth1.*(dph1.*(t9.*3.26e-3+t11.*(2.38e+2./6.25e+2)).*2.49975e-1+dth1.*(t9.*8.149185e-4+t11.*9.519048e-2+sin(th1).*9.35690184e-2));
et4 = dph1.*t5.*(t9.*1.63e-3+t11.*(1.19e+2./6.25e+2)).*(-4.9995e-1)-dph2.*t6.*t12.*4.580069e-2;
C = [et1+et2;et3+et4;dph1.*t15.*(dth1+t5).*(-8.7241275e-2);dph2.*t4.*(dth2+t6).*(-7.992220405e-3);dth1.^2.*t15.*8.7241275e-2;dth2.^2.*t4.*7.992220405e-3];
end
