function dH = dH_calc_func(th1,th2,ph1,ph2,dth1,dth2,dph1,dph2)
%dH_calc_func
%    dH = dH_calc_func(TH1,TH2,PH1,PH2,DTH1,DTH2,DPH1,DPH2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    23-Jul-2025 14:08:30

t2 = dph1+dth1;
t3 = dph2+dth2;
t4 = ph1+th1;
t5 = ph2+th2;
t6 = cos(t4);
t7 = cos(t5);
t8 = sin(t4);
t9 = sin(t5);
dH = reshape([0.0,0.0,0.0,0.0,-dth1.*(t6.*2.955e-1+cos(th1).*1.745e-1)-dph1.*t6.*2.955e-1,dph1.*t8.*(-2.955e-1)-dth1.*(t8.*2.955e-1+sin(th1).*1.745e-1),dth2.*(t7.*(3.0./1.0e+1)+cos(th2).*1.745e-1)+dph2.*t7.*(3.0./1.0e+1),dph2.*t9.*(3.0./1.0e+1)+dth2.*(t9.*(3.0./1.0e+1)+sin(th2).*1.745e-1),t2.*t6.*(-2.955e-1),t2.*t8.*(-2.955e-1),t3.*t7.*(3.0./1.0e+1),t3.*t9.*(3.0./1.0e+1)],[2,6]);
end
