function dJ = dJ_calc_func(th1,th2,ph1,ph2,dth1,dth2,dph1,dph2)
%dJ_calc_func
%    dJ = dJ_calc_func(TH1,TH2,PH1,PH2,DTH1,DTH2,DPH1,DPH2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    23-Jul-2025 14:08:30

t2 = dph1+dth1;
t3 = ph1+th1;
t6 = pi.*(2.0./9.0);
t7 = pi.*(3.1e+1./1.8e+1);
t4 = cos(t3);
t5 = sin(t3);
t8 = t3+t6;
t9 = t3+t7;
t10 = cos(t9);
t11 = sin(t9);
t12 = t4.*2.955e-1;
t13 = t5.*2.955e-1;
t14 = t10.*(2.1e+1./8.0e+2);
t15 = t11.*(2.1e+1./8.0e+2);
dJ = reshape([0.0,0.0,0.0,0.0,-dph1.*(t12+t14)-dth1.*(t12+t14+cos(th1).*1.745e-1),-dph1.*(t13+t15)-dth1.*(t13+t15+sin(th1).*1.745e-1),0.0,0.0,-t2.*(t12+sin(t8).*(2.1e+1./8.0e+2)),-t2.*(t13-cos(t8).*(2.1e+1./8.0e+2)),0.0,0.0],[2,6]);
end
