function kinematics_foot = foot_Func(x,y,th1,th2,ph1,dx,dy,dth1,dth2,dph1)
%foot_Func
%    KINEMATICS_FOOT = foot_Func(X,Y,TH1,TH2,PH1,DX,DY,DTH1,DTH2,DPH1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    02-Oct-2025 09:09:54

t2 = cos(th1);
t3 = sin(th1);
t4 = ph1+th1;
t7 = pi.*(3.1e+1./1.8e+1);
t5 = cos(t4);
t6 = sin(t4);
t8 = t4+t7;
t9 = t2.*1.745e-1;
t10 = t3.*1.745e-1;
t11 = cos(t8);
t12 = sin(t8);
t13 = t5.*2.955e-1;
t14 = t6.*2.955e-1;
t15 = t11.*(2.1e+1./8.0e+2);
t16 = t12.*(2.1e+1./8.0e+2);
kinematics_foot = reshape([t9+t13+t15+x-3.0./5.0e+1,t10+t14+t16+y-1.3e+1./8.0e+2,dx-dph1.*(t14+t16)-dth1.*(t10+t14+t16),dy+dph1.*(t13+t15)+dth1.*(t9+t13+t15)],[2,2]);
end
