function G = G_calc_func(x,y,th1,th2,ph1,ph2)
%G_calc_func
%    G = G_calc_func(X,Y,TH1,TH2,PH1,PH2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    02-Oct-2025 09:09:53

t2 = ph1+th1;
t3 = ph2+th2;
t4 = cos(t2);
t5 = cos(t3);
t6 = sin(t2);
t7 = t4.*9.338186088e-1;
t8 = t5.*4.493047689e-1;
t9 = t6.*7.994350485e-3;
t10 = -t9;
G = [0.0;3.64330647e+1;t7+t10+cos(th1).*9.17912070504e-1;t8+cos(th2).*6.55143863004e-1;t7+t10;t8];
end
