function H = H_calc_func(th1,th2,ph1,ph2)
%H_calc_func
%    H = H_calc_func(TH1,TH2,PH1,PH2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    23-Jul-2025 14:08:31

t2 = ph1+th1;
t3 = ph2+th2;
t4 = cos(t2);
t5 = cos(t3);
t6 = sin(t2);
t7 = sin(t3);
t8 = t5.*(3.0./1.0e+1);
t9 = t7.*(3.0./1.0e+1);
t11 = t4.*2.955e-1;
t12 = t6.*2.955e-1;
t10 = -t8;
t13 = -t12;
H = reshape([0.0,0.0,0.0,0.0,t13-sin(th1).*1.745e-1,t11+cos(th1).*1.745e-1,t9+sin(th2).*1.745e-1,t10-cos(th2).*1.745e-1,t13,t11,t9,t10],[2,6]);
end
