function ph2 = ph2_calc(th1,th2)
%PH2_CALC
%    PH2 = PH2_CALC(TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    10-Sep-2025 11:13:56

t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = t2.*1.745e-1;
t7 = t3.*1.745e-1;
t8 = t4.*1.745e-1;
t9 = t5.*1.745e-1;
t10 = -t6;
t11 = -t9;
t12 = t8+t11;
t14 = t7+t10+3.0./2.5e+1;
t13 = t12.^2;
t15 = t14.^2;
ph2 = -th2+pi+asin(sqrt(((t13+t15-2.679750000000012e-3).^2.*(-2.863024327117708))./(t13+t15)+1.0).*(1.97e+2./2.0e+2))+atan2(t4.*(-1.745e-1)+t5.*1.745e-1,t14);
end
