function Q = Q_calc_func(th1,th2,ph1,ph2,dth1,dth2,dph1,dph2,f_cx,f_cy,grf_n,grf_t,t1,t2)
%Q_calc_func
%    Q = Q_calc_func(TH1,TH2,PH1,PH2,DTH1,DTH2,DPH1,DPH2,F_CX,F_CY,GRF_N,GRF_T,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jul-2025 13:26:21

t4 = cos(th1);
t5 = sin(th1);
t6 = ph1+th1;
t7 = ph2+th2;
t12 = pi.*(2.0./9.0);
t8 = cos(t6);
t9 = cos(t7);
t10 = sin(t6);
t11 = sin(t7);
t13 = t6+t12;
t16 = t4.*1.745e-1;
t17 = t5.*1.745e-1;
t14 = cos(t13);
t15 = sin(t13);
t18 = t8.*2.955e-1;
t19 = t10.*2.955e-1;
t20 = t14.*(2.1e+1./8.0e+2);
t21 = t15.*(2.1e+1./8.0e+2);
Q = [grf_t;grf_n;t1+f_cy.*(t16+t18)-f_cx.*(t17+t19)+grf_n.*(t16+t18+t21)-grf_t.*(t17+t19-t20);t2-f_cy.*(t9.*(3.0./1.0e+1)+cos(th2).*1.745e-1)+f_cx.*(t11.*(3.0./1.0e+1)+sin(th2).*1.745e-1);grf_n.*(t18+t21)-f_cx.*t10.*2.955e-1+f_cy.*t18-grf_t.*(t19-t20);f_cy.*t9.*(-3.0./1.0e+1)+f_cx.*t11.*(3.0./1.0e+1)];
end
