function Q_t = Q_t_calc_func(th1,th2,ph1,ph2,dth1,dth2,dph1,dph2,t1,t2)
%Q_t_calc_func
%    Q_t = Q_t_calc_func(TH1,TH2,PH1,PH2,DTH1,DTH2,DPH1,DPH2,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    10-Sep-2025 11:13:21

Q_t = [0.0;0.0;dth1.*(-1.0./1.0e+2)+t1;dth2.*(-1.0./1.0e+2)+t2;0.0;0.0];
end
