function dH = dH_calc_func(th1,th2,th3,th4,ph1,ph2,ph3,ph4,dth1,dth2,dth3,dth4,dph1,dph2,dph3,dph4)
%dH_calc_func
%    dH = dH_calc_func(TH1,TH2,TH3,TH4,PH1,PH2,PH3,PH4,DTH1,DTH2,DTH3,DTH4,DPH1,DPH2,DPH3,DPH4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    11-Sep-2025 13:03:44

t2 = dph1+dth1;
t3 = dph2+dth2;
t4 = dph3+dth3;
t5 = dph4+dth4;
t6 = ph1+th1;
t7 = ph2+th2;
t8 = ph3+th3;
t9 = ph4+th4;
t10 = cos(t6);
t11 = cos(t7);
t12 = cos(t8);
t13 = cos(t9);
t14 = sin(t6);
t15 = sin(t7);
t16 = sin(t8);
t17 = sin(t9);
mt1 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dth1.*(t10.*2.955e-1+cos(th1).*1.745e-1)-dph1.*t10.*2.955e-1,dph1.*t14.*(-2.955e-1)-dth1.*(t14.*2.955e-1+sin(th1).*1.745e-1),0.0,0.0,dth2.*(t11.*(3.0./1.0e+1)+cos(th2).*1.745e-1)+dph2.*t11.*(3.0./1.0e+1),dph2.*t15.*(3.0./1.0e+1)+dth2.*(t15.*(3.0./1.0e+1)+sin(th2).*1.745e-1),0.0,0.0,0.0,0.0,-dth3.*(t12.*2.955e-1+cos(th3).*1.745e-1)-dph3.*t12.*2.955e-1];
mt2 = [dph3.*t16.*(-2.955e-1)-dth3.*(t16.*2.955e-1+sin(th3).*1.745e-1),0.0,0.0,dth4.*(t13.*(3.0./1.0e+1)+cos(th4).*1.745e-1)+dph4.*t13.*(3.0./1.0e+1),dph4.*t17.*(3.0./1.0e+1)+dth4.*(t17.*(3.0./1.0e+1)+sin(th4).*1.745e-1),t2.*t10.*(-2.955e-1),t2.*t14.*(-2.955e-1),0.0,0.0,t3.*t11.*(3.0./1.0e+1),t3.*t15.*(3.0./1.0e+1),0.0,0.0,0.0,0.0,t4.*t12.*(-2.955e-1),t4.*t16.*(-2.955e-1),0.0,0.0,t5.*t13.*(3.0./1.0e+1),t5.*t17.*(3.0./1.0e+1)];
dH = reshape([mt1,mt2],4,10);
end
