function dJ_b = dJ_b_calc_func(th1,th2,th3,th4,ph1,ph2,ph3,ph4,dth1,dth2,dth3,dth4,dph1,dph2,dph3,dph4)
%dJ_b_calc_func
%    dJ_b = dJ_b_calc_func(TH1,TH2,TH3,TH4,PH1,PH2,PH3,PH4,DTH1,DTH2,DTH3,DTH4,DPH1,DPH2,DPH3,DPH4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    11-Sep-2025 13:03:45

t2 = dph3+dth3;
t3 = ph3+th3;
t6 = pi.*(2.0./9.0);
t7 = pi.*(3.1e+1./1.8e+1);
t4 = cos(t3);
t5 = sin(t3);
t8 = t3+t6;
t9 = t3+t7;
t10 = cos(t9);
t11 = sin(t9);
t12 = t4.*2.955e-1;
t13 = t5.*2.955e-1;
t14 = t10.*(2.1e+1./8.0e+2);
t15 = t11.*(2.1e+1./8.0e+2);
dJ_b = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dph3.*(t12+t14)-dth3.*(t12+t14+cos(th3).*1.745e-1),-dph3.*(t13+t15)-dth3.*(t13+t15+sin(th3).*1.745e-1),0.0,0.0,0.0,0.0,0.0,0.0,-t2.*(t12+sin(t8).*(2.1e+1./8.0e+2)),-t2.*(t13-cos(t8).*(2.1e+1./8.0e+2)),0.0,0.0],[2,10]);
end
