function G = G_calc_func(x,y,th1,th2,th3,th4,ph1,ph2,ph3,ph4)
%G_calc_func
%    G = G_calc_func(X,Y,TH1,TH2,TH3,TH4,PH1,PH2,PH3,PH4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    11-Sep-2025 13:03:44

t2 = ph1+th1;
t3 = ph2+th2;
t4 = ph3+th3;
t5 = ph4+th4;
t6 = cos(t2);
t7 = cos(t3);
t8 = cos(t4);
t9 = cos(t5);
t10 = sin(t2);
t11 = sin(t4);
t12 = t6.*9.338186088e-1;
t13 = t8.*9.338186088e-1;
t14 = t7.*4.493047689e-1;
t15 = t9.*4.493047689e-1;
t16 = t10.*7.994350485e-3;
t17 = t11.*7.994350485e-3;
t18 = -t16;
t19 = -t17;
G = [0.0;7.66768239e+1;t12+t18+cos(th1).*9.17912070504e-1;t14+cos(th2).*6.55143863004e-1;t13+t19+cos(th3).*9.17912070504e-1;t15+cos(th4).*6.55143863004e-1;t12+t18;t14;t13+t19;t15];
end
