function H = H_calc_func(th1,th2,th3,th4,ph1,ph2,ph3,ph4)
%H_calc_func
%    H = H_calc_func(TH1,TH2,TH3,TH4,PH1,PH2,PH3,PH4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    11-Sep-2025 13:03:44

t2 = ph1+th1;
t3 = ph2+th2;
t4 = ph3+th3;
t5 = ph4+th4;
t6 = cos(t2);
t7 = cos(t3);
t8 = cos(t4);
t9 = cos(t5);
t10 = sin(t2);
t11 = sin(t3);
t12 = sin(t4);
t13 = sin(t5);
t14 = t7.*(3.0./1.0e+1);
t15 = t9.*(3.0./1.0e+1);
t16 = t11.*(3.0./1.0e+1);
t17 = t13.*(3.0./1.0e+1);
t20 = t6.*2.955e-1;
t21 = t8.*2.955e-1;
t22 = t10.*2.955e-1;
t23 = t12.*2.955e-1;
t18 = -t14;
t19 = -t15;
t24 = -t22;
t25 = -t23;
H = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t24-sin(th1).*1.745e-1,t20+cos(th1).*1.745e-1,0.0,0.0,t16+sin(th2).*1.745e-1,t18-cos(th2).*1.745e-1,0.0,0.0,0.0,0.0,t25-sin(th3).*1.745e-1,t21+cos(th3).*1.745e-1,0.0,0.0,t17+sin(th4).*1.745e-1,t19-cos(th4).*1.745e-1,t24,t20,0.0,0.0,t16,t18,0.0,0.0,0.0,0.0,t25,t21,0.0,0.0,t17,t19],[4,10]);
end
