function J_b = J_b_calc_func(th1,th2,th3,th4,ph1,ph2,ph3,ph4)
%J_b_calc_func
%    J_b = J_b_calc_func(TH1,TH2,TH3,TH4,PH1,PH2,PH3,PH4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    11-Sep-2025 13:03:45

t2 = ph3+th3;
t5 = pi.*(2.0./9.0);
t3 = cos(t2);
t4 = sin(t2);
t6 = t2+t5;
t7 = cos(t6);
t8 = sin(t6);
t9 = t3.*2.955e-1;
t10 = t4.*2.955e-1;
t11 = -t10;
t12 = t7.*(2.1e+1./8.0e+2);
t13 = t8.*(2.1e+1./8.0e+2);
J_b = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,t11+t12-sin(th3).*1.745e-1,t9+t13+cos(th3).*1.745e-1,0.0,0.0,0.0,0.0,0.0,0.0,t11+t12,t9+t13,0.0,0.0],[2,10]);
end
