function Q_t = Q_t_calc_func(th1,th2,th3,th4,ph1,ph2,ph3,ph4,dth1,dth2,dth3,dth4,dph1,dph2,dph3,dph4,t1,t2,t3,t4)
%Q_t_calc_func
%    Q_t = Q_t_calc_func(TH1,TH2,TH3,TH4,PH1,PH2,PH3,PH4,DTH1,DTH2,DTH3,DTH4,DPH1,DPH2,DPH3,DPH4,T1,T2,T3,T4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    11-Sep-2025 13:03:44

Q_t = [0.0;0.0;dth1.*(-1.0./1.0e+2)+t1;dth2.*(-1.0./1.0e+2)+t2;dth3.*(-1.0./1.0e+2)+t3;dth4.*(-1.0./1.0e+2)+t4;0.0;0.0;0.0;0.0];
end
