function Q_t = Q_t_calc_func(x,y,th1,th2,ph1,ph2,dx,dy,dth1,dth2,dph1,dph2,t1,t2)
%Q_t_calc_func
%    Q_t = Q_t_calc_func(X,Y,TH1,TH2,PH1,PH2,DX,DY,DTH1,DTH2,DPH1,DPH2,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    02-Oct-2025 09:09:53

t4 = y-1.01e+2./1.0e+3;
t5 = t4.^2;
t6 = t5.*1.608997772986182e-1;
Q_t = [0.0;sqrt(-t6+1.0).*3.64330647e+1-(dy.^2.*t4.*5.975608559160193e-1)./(t6-1.0)-3.64330647e+1;dth1.*(-1.0./1.0e+2)+t1;dth2.*(-1.0./1.0e+2)+t2;0.0;0.0];
end
